database:
  clash-verge:
    type: category
    prefix: /home/lialh4/.local/share/io.github.clash-verge-rev.clash-verge-rev
    database:
      script:
        type: file
        src: profiles/Script.js
        dist: script.js
