database:
  - name: clash-verge
    type: category
    prefix: /home/lialh4/.local/share/io.github.clash-verge-rev.clash-verge-rev
    database:
      - name: profiles
        type: category
        prefix: profiles
        database:
          - name: script
            type: file
            src: Script.js
            dist: script.js
