- id: ID_98um76d5
  name: Default
  log:
    disabled: true
    level: info
    output: ""
    timestamp: false
  experimental:
    clash_api:
      external_controller: localhost:20123
      external_ui: ""
      external_ui_download_url: ""
      external_ui_download_detour: outbound-urlte
      secret: ""
      default_mode: rule
      access_control_allow_origin:
        - "*"
      access_control_allow_private_network: false
    cache_file:
      enabled: true
      path: cache.db
      cache_id: ""
      store_fakeip: true
      store_rdrc: true
      rdrc_timeout: 7d
  inbounds:
    - id: tun-in
      type: tun
      tag: tun-in
      enable: true
      tun:
        interface_name: mihoyo
        address:
          - 172.18.0.1/30
          - fdfe:dcba:9876::1/126
        mtu: 9000
        auto_route: true
        strict_route: true
        route_address: []
        endpoint_independent_nat: false
        stack: mixed
    - id: ID_2ydn6r1k
      tag: mixed-in
      type: mixed
      enable: true
      mixed:
        listen:
          listen: 127.0.0.1
          listen_port: 20122
          tcp_fast_open: false
          tcp_multi_path: false
          udp_fragment: false
        users: []
  outbounds:
    - id: outbound-direct
      tag: Direct
      type: direct
      outbounds: []
      interrupt_exist_connections: true
      url: ""
      interval: 3m
      tolerance: 150
      include: ""
      exclude: ""
    - id: outbound-urlte
      tag: Proxy
      type: urltest
      outbounds:
        - id: ID_n28tz3zk
          tag: ID_n28tz3zk
          type: Subscription
      interrupt_exist_connections: true
      url: https://www.gstatic.com/generate_204
      interval: 3m
      tolerance: 150
      include: HK|JP
      exclude: NF|直连
  route:
    rules:
      - id: ID_6tk60wd2
        type: inbound
        payload: tun-in
        invert: false
        action: sniff
        outbound: ""
        sniffer: []
        strategy: default
        server: ""
      - id: ID_svlaahq1
        type: protocol
        payload: dns
        invert: false
        action: hijack-dns
        outbound: ""
        sniffer: []
        strategy: default
        server: ""
      - id: ID_78k3rt6g
        type: protocol
        payload: quic
        invert: false
        action: reject
        outbound: ""
        sniffer: []
        strategy: default
        server: ""
      - id: ID_xukciajg
        type: clash_mode
        payload: direct
        invert: false
        action: route
        outbound: outbound-direct
        sniffer: []
        strategy: default
        server: ""
      - id: ID_kl6xfvqt
        type: clash_mode
        payload: global
        invert: false
        action: route
        outbound: outbound-urlte
        sniffer: []
        strategy: default
        server: ""
      - id: ID_fyorq14e
        type: rule_set
        payload: GeoSite-Private
        invert: false
        action: route
        outbound: outbound-direct
        sniffer: []
        strategy: default
        server: ""
      - id: ID_oep3ql8g
        type: rule_set
        payload: GeoIP-Private
        invert: false
        action: route
        outbound: outbound-direct
        sniffer: []
        strategy: default
        server: ""
      - id: ID_bgf5q61c
        type: rule_set
        payload: GeoSite-CN
        invert: false
        action: route
        outbound: outbound-direct
        sniffer: []
        strategy: default
        server: ""
      - id: ID_fuyrhzk4
        type: rule_set
        payload: GeoIP-CN
        invert: false
        action: route
        outbound: outbound-direct
        sniffer: []
        strategy: default
        server: ""
    rule_set:
      - id: GeoIP-Private
        type: remote
        tag: GeoIP-Private
        format: binary
        url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/private.srs
        download_detour: outbound-urlte
        update_interval: 1d
        rules: ""
        path: ""
      - id: GeoSite-Private
        type: remote
        tag: GeoSite-Private
        format: binary
        url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/private.srs
        download_detour: outbound-urlte
        update_interval: 1d
        rules: ""
        path: ""
      - id: GeoIP-CN
        type: remote
        tag: GeoIP-CN
        format: binary
        url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs
        download_detour: outbound-urlte
        update_interval: 1d
        rules: ""
        path: ""
      - id: GeoSite-CN
        type: remote
        tag: GeoSite-CN
        format: binary
        url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs
        download_detour: outbound-direct
        update_interval: ""
        rules: ""
        path: ""
    auto_detect_interface: true
    default_interface: ""
    final: outbound-urlte
    find_process: false
    default_domain_resolver:
      server: Local-DNS
      client_subnet: ""
  dns:
    servers:
      - id: Local-DNS
        tag: Local-DNS
        detour: ""
        type: https
        domain_resolver: ""
        server: 223.5.5.5
        server_port: "443"
        path: /dns-query
        interface: ""
        inet4_range: ""
        inet6_range: ""
        hosts_path: []
        predefined: {}
      - id: Remote-DNS
        tag: Remote-DNS
        detour: ""
        type: https
        domain_resolver: ""
        server: 8.8.8.8
        server_port: "443"
        path: /dns-query
        interface: ""
        inet4_range: ""
        inet6_range: ""
        hosts_path: []
        predefined: {}
    rules:
      - id: ID_ga04jcq3
        type: clash_mode
        payload: direct
        action: route
        server: Local-DNS
        invert: false
        strategy: default
        disable_cache: false
        client_subnet: ""
      - id: ID_t0oo9xnx
        type: clash_mode
        payload: global
        action: route
        server: Remote-DNS
        invert: false
        strategy: default
        disable_cache: false
        client_subnet: ""
      - id: ID_bga7cqsv
        type: rule_set
        payload: GeoSite-CN
        action: route
        server: Local-DNS
        invert: false
        strategy: default
        disable_cache: false
        client_subnet: ""
    disable_cache: false
    disable_expire: false
    independent_cache: false
    client_subnet: ""
    final: Remote-DNS
    strategy: default
  mixin:
    priority: mixin
    config: "{}"
  script:
    code: |-
      const onGenerate = async (config) => {
        return config
      }
